name: Build + Publish (GHCR)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
  schedule:
    - cron: "29 2 * * 1"

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: securelayer-labs/base-alpine

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        alpine_version: ["3.23.3"]
        alpine_line: ["3.23"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (multi-arch) + SBOM/Provenance Attestations
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.alpine_line }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.alpine_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-alpine${{ matrix.alpine_version }}
          provenance: true
          sbom: true

      - name: Image reference (digest)
        id: img
        run: |
          echo "IMMUTABLE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.buildpush.outputs.digest }}" >> $GITHUB_OUTPUT

      - name: Trivy Scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ steps.img.outputs.IMMUTABLE }}
          format: sarif
          output: trivy-alpine.sarif
          ignore-unfixed: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-alpine.sarif

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: Cosign sign (keyless)
        run: |
          cosign sign --yes ${{ steps.img.outputs.IMMUTABLE }}

      - name: Generate SBOM (SPDX JSON) with Syft
        uses: anchore/sbom-action@v0
        with:
          image: ${{ steps.img.outputs.IMMUTABLE }}
          format: spdx-json
          output-file: sbom-alpine.spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-alpine
          path: sbom-alpine.spdx.json
